resources:
  database:
    type: postgres
  redis:
    type: redis

services:
  web:
    build: .
    port: 3000
    environment:
      - SECRET_KEY_BASE=update-this-key-in-the-console
    resources:
      - database
      - redis
