version: "3"
services:
  db:
    container_name: video-ror-db
    image: postgres:13
    expose:
      - 5432
    volumes:
      - /docker-run/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: video_password
      POSTGRES_USER: video

  redis:
    container_name: video-ror-redis
    image: redis:latest
    volumes:
      - 'redis:/data'
    ports:
      - "6379:6379"

  app:
    container_name: video-ror
    image: vokythoai/video:video.1.0.1
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    expose:
      - 3000
    env_file:
      - ./.env.docker_compose
    tty: true
    environment:
      VIRTUAL_HOST: 3.0.57.115
      LETSENCRYPT_HOST: 3.0.57.115

  sidekiq:
    container_name: video-ror-sidekiq
    image: vokythoai/video:video.1.0.1
    depends_on:
      - db
      - redis
      - app
    entrypoint: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    env_file:
      - ./.env.docker_compose
    tty: true

  nginx:
    image: nginx:latest
    restart: 'unless-stopped'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "20"
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
    container_name: reverse
    volumes:
      - /docker-run/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /docker-run/nginx/ssl:/etc/nginx/ssl
    network_mode: host

volumes:
  redis:
  postgres:
  sidekiq:
  gem_cache:
